### ISSUE TITLE
How can I send a M150 to change the LEDs from anywhere in the code?

### ISSUE THREAD

**Issue by tjthejuggler** [MasterPuffin/MKS-GEN-L-V2-Marlin-Firmware-for-Ender-3#1]
This isn't exactly an issue, I'm sorry, I just don't know where else to ask. We have spent so many hours trying to send a M150 command to change the LED color at line 574 of temperature.cpp where it says

_temp_error(heater_id, str_t_heating_failed, GET_TEXT(MSG_HEATING_FAILED_LCD));

and we are so stuck. We just want the lights to change when that message pops up. I feel like it shouldn't be that hard, but I also feel like we have tried everything. Can someone please tell me what we need to put there to do this? Thank you so much!  Any help is greatly appreciated!

edit:
I totally forgot to say - Thanks so much for making all this! This is an incredible amount of work, I really appreciate all the time and effort you have put into this MasterPuffin!

**Comment by MasterPuffin** [comment]
Hello, thank you for your kind words. As this is an issue with the Marlin firmware and not my modifications I would suggest asking there for help - as you already did.
I'll link the issue for further references: https://github.com/MarlinFirmware/Marlin/issues/22154
